// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3gqQh3vEHAbaCzI7czhMMjCP_U_b3TBI',
    appId: '1:809963843236:web:dcd7211f5f0d5370a50031',
    messagingSenderId: '809963843236',
    projectId: 'inlet-925d1',
    authDomain: 'inlet-925d1.firebaseapp.com',
    storageBucket: 'inlet-925d1.firebasestorage.app',
    measurementId: 'G-R57FDMYT30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdlYXkbNx8HyHnMCzV33D-20T20rBTKq4',
    appId: '1:809963843236:android:6fdf7018c3bc9a6aa50031',
    messagingSenderId: '809963843236',
    projectId: 'inlet-925d1',
    storageBucket: 'inlet-925d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvicz_5ZmaRvcFR3Mk5FP1rEbM6VO6eqQ',
    appId: '1:809963843236:ios:28858be116d81f46a50031',
    messagingSenderId: '809963843236',
    projectId: 'inlet-925d1',
    storageBucket: 'inlet-925d1.firebasestorage.app',
    iosBundleId: 'com.example.inlet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3gqQh3vEHAbaCzI7czhMMjCP_U_b3TBI',
    appId: '1:809963843236:web:9881362d458b1e3ca50031',
    messagingSenderId: '809963843236',
    projectId: 'inlet-925d1',
    authDomain: 'inlet-925d1.firebaseapp.com',
    storageBucket: 'inlet-925d1.firebasestorage.app',
    measurementId: 'G-6JVEL9Q90G',
  );
}
