import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
//import 'supabase_client.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'services/auth_service.dart';
import 'pages/auth/login_page.dart';
import 'pages/resident/resident_home.dart';
import 'pages/admin/admin_panel.dart';
import 'pages/guard/guard_home.dart';
//import 'package:inlet/supabase_connection_test.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'firebase_options.dart'; // auto-generated by Firebase CLI
import 'pages/splash_page.dart';


final navigatorKey = GlobalKey<NavigatorState>();
@pragma('vm:entry-point') // 👈 this line is critical!
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  // Handle background message (optional)
  debugPrint('🔔 Background message ${message.messageId}');
}

/*Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // handle background message if needed
  print('Background message: ${message.notification?.title}');
}*/

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

/*Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print("🔔 Background message: ${message.notification?.title}");
}
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  //await Supa.init();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);*/
  await Supabase.initialize(
    url: 'https://xzzgxebsrkizirygmqmg.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6emd4ZWJzcmtpemlyeWdtcW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTkxODMsImV4cCI6MjA3NDU3NTE4M30.ytdrVGhBx6cpfEb98LsQlntatssuF-IP578bYH45A24',
  );
 /* FirebaseMessaging.onMessage.listen((message) {
    ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(message.notification?.body ?? ''))
    );
  });*/

  /*FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    final n = message.notification;
    if (n != null) {
      // show simple dialog using navigatorKey
      showDialog(
        context: navigatorKey.currentContext!,
        builder: (_) => AlertDialog(
          title: Text(n.title ?? ''),
          content: Text(n.body ?? ''),
          actions: [TextButton(onPressed: () => Navigator.pop(_), child: Text('OK'))],
        ),
      );
    }
  });*/

  FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
    // handle when user taps notification
    final data = message.data;
    // navigate or update UI depending on data
  });

  /*FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    if (message.notification != null) {
      final notification = message.notification!;
      showDialog(
        context: navigatorKey.currentContext!,
        builder: (_) => AlertDialog(
          title: Text(notification.title ?? 'Notification'),
          content: Text(notification.body ?? ''),
          actions: [TextButton(onPressed: () => Navigator.pop(_), child: const Text('OK'))],
        ),
      );
    }
  }*/



  runApp(const InletApp());
}

class InletApp extends StatelessWidget {
  const InletApp({super.key});
  @override Widget build(BuildContext context) {
    return ChangeNotifierProvider(create: (_) => AuthService(), child: Consumer<AuthService>(
      builder: (context, auth, _) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          navigatorKey: navigatorKey, // ✅ Add this line
          title: 'Inlet',
          theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.indigo),
          home: const SplashPage(),
         // home: _buildHome(auth),
          //home: const SupabaseConnectionTest(),
          routes: {
            '/login': (_) => const LoginPage(),
            '/resident': (_) =>const ResidentHome(),
            '/admin': (_) => const AdminMainPage(),
            '/guard': (_) => const GuardHome(),
          },
        );
      },
    ));
  }

  Widget _buildHome(AuthService auth) {
   // if (auth.isLoading) return const Scaffold(body: Center(child: CircularProgressIndicator()));
    if (auth.currentUser == null) return const LoginPage();
    final role = auth.currentUser?.role ?? 'Resident';
    if (role == 'Admin') return const AdminMainPage();
    if (role == 'Guard') return const GuardHome();
    return ResidentHome();
  }
}
